name: CI

on: [push]

jobs:
  run:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: [14, 18, 19]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: install
        run: |
          npm install
        env:
          CI: true
      - name: lint
        run: |
          npm run lint
      - name: test
        run: npm test
        env:
          CI: true
      - name: build
        run: npm run build
